name: "verify-kinds"

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.cue'

jobs:
  main:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Grafana repo"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Setup Go"
        uses: "actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c"
        with:
          go-version-file: go.mod

      - name: "Verify kinds"
        run: go run .github/workflows/scripts/kinds/verify-kinds.go
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
